import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import BottomNavbar from "./components/BottomNavbar";
import { ContextProvider } from "./context/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cure Medical App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
      <html lang="en">
        <body className="bg-base-200">
          <Navbar />
          {children}
          <BottomNavbar/>
        </body>
      </html>
    </ContextProvider>
  );
}
